name: 👻 metrics

on:
  schedule: [{ cron: "0 16 * * *" }]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: profile
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: profile.svg
          token: ${{ secrets.TOKEN }}
          base: header, activity, community, repositories
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
      - name: contributions
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: contributions.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          config_order: languages, isocalendar
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, ejs
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_isocalendar: yes
